# Generated by Django 5.1.3 on 2024-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
